// 網站文字（由後台編輯器產生；值可含 HTML）
const SITE = {
  "page.title": "PP YAO — 12th Anniversary",
  "home.label": "✦ 宇宙手帖",
  "home.url": "https://takaoyc.github.io/pp_uchutecho/index.html",
  "hero.name": "PP YAO",
  "hero.sub": "12th ANNIVERSARY",
  "hero.note": "非官方・非營利紀念企劃",
  "hero.scroll": "SCROLL",
  "book.kicker": "COMMEMORATIVE PUBLICATION",
  "book.title": "出道十二週年紀念",
  "book.credit": "文　字<b>ㄅ級分的煙機</b>",
  "book.desc": "乘著光影而來的馭墨者。將那些在黑夜裡翻湧的感受，一筆一劃，落成白紙上的深沉回聲。選取十二部作品，寫成兩個篇章——「在不同之間，看見彼此」與「在青春散場以前，留下些什麼」。",
  "book.hint": "✦ 點擊書本封面閱讀",
  "book.features": "<span>✦ 字級調整</span><span>✦ 頁面深淺</span><span>✦ 直排/橫排</span>",
  "reader.title": "姚愛寗出道十二週年紀念",
  "map.kicker": "CONSTELLATION OF WORKS",
  "map.title": "作 品 星 系",
  "map.note": "十二年的軌跡，凝成一座星系。<br>每一部作品，都是一顆自轉的星球——沿著旋臂輕觸，或緩緩下滑，逐一造訪。",
  "mv.kicker": "MUSIC VIDEO NEBULA",
  "mv.title": "MV 星 雲",
  "mv.note": "散落在星系外緣的光點，每一支 MV，都是一次短暫而明亮的閃爍。<br>輕觸星光，前往觀看。",
  "iv.kicker": "INTERVIEW ORBIT",
  "iv.title": "訪 談 星 軌",
  "iv.note": "十二年間散落各處的訪談與紀錄，沿時間軌道排列。<br>與作品直接相關的訪談，已同步收錄於各自的星球頁。",
  "footer.fin": "PP YAO · 12TH ANNIVERSARY",
  "footer.sub": "FROM THE FIRST STAR, AND ONWARD",
  "footer.orn": "✦ &nbsp; ✧ &nbsp; ✦",
  "footer.ver": "ver 2026.09.01-3"
};
